## SEP 2026 - MLP - Graded Assignment 1.2
### Week 1 Pandas

### Data Loading

In [1]:
import numpy as np
import pandas as pd

Check your data properly with the assignment

In [2]:
file_id = '1x-phOl0d1QHy4ea8O_hHdz_wBGH35dRz'
df = pd.read_csv(f'https://drive.google.com/uc?id={file_id}')

In [3]:
df.shape

(10000, 12)

In [4]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

### Q1

In [5]:
ans = df.iloc[::2,:].iloc[0,3]
print(ans)

111440.0

### Q2

In [6]:
ans = df.iloc[::2,:].iloc[332,3]
print(ans)

256200.0

### Q3

In [7]:
ans = df.iloc[1::2,].iloc[332,3]
print(ans)

352940.0

### Q4

In [8]:
ans = df.iloc[:,1::2].iloc[100,5]
print(ans)

West

### Q5

In [9]:
ans = df.iloc[::2,::2].iloc[255,3]
print(ans)

Detached House

### Q6

In [10]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [11]:
df['Year'].unique()

array([2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
       2020, 2021, 2022])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  object
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   object
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           10000 non-null  object
 6   Residential        10000 non-null  object
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  object
dtypes: float64(4), int64(3), object(5)
memory usage: 937.6+ KB

In [13]:
df['Year'].max(), df['Year'].max()-6

(2022, 2016)

In [14]:
df[ df['Year'] > df['Year'].max()-6 ].shape[0]

4749

### Q7

In [15]:
df[ (df['num_rooms']==3) & (df['num_bathrooms']==3) ].shape[0]

2730

### Q8

In [16]:
df[ (df['num_rooms']==3) | (df['num_bathrooms']==3) ].shape[0]

8591

### Q9

In [17]:
df[ (df['Year']==2022) & (df['Locality']=='Greenwich') & (df['num_rooms']==3) & ( (df['Face']=="North") | (df['Face']=="East") ) ].shape[0]

42

### Q10

In [18]:
ans = df['Date'].str.contains('-08-').sum()
print(ans)

1050

In [19]:
df[ df['Date'].apply( lambda x: int(x.strip().split('-')[1]) == 8 ) ].shape[0]

1050

### Q11

In [20]:
df[['Locality', 'Sale Price']].groupby('Locality').mean()['Sale Price']

Locality
Bridgeport       1.740953e+05
Fairfield        7.277225e+05
Greenwich        2.270224e+06
Norwalk          5.590959e+05
Stamford         6.305313e+05
Waterbury        1.062152e+05
West Hartford    3.385472e+05
Name: Sale Price, dtype: float64