## SEP 2026 - MLP - Graded Assignment 1.1
### Week 1 Pandas

### Data Loading

In [1]:
import numpy as np
import pandas as pd

Check your data properly with the assignment

In [2]:
file_id = '1x-phOl0d1QHy4ea8O_hHdz_wBGH35dRz'
df = pd.read_csv(f'https://drive.google.com/uc?id={file_id}')

In [3]:
df.shape

(10000, 12)

In [4]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

### Q1

In [5]:
df == '?'

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,True,False,False,False,False,False,False
9996,False,False,False,False,False,True,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
unknown_count = (df == '?').sum().sum()
print(unknown_count)

df = df.replace('?', np.nan)

1823

### Q2

In [7]:
df.shape

(10000, 12)

### Q3

In [8]:
df.iloc[692, 0]

'2009-11-16'

### Q4

In [9]:
print(df.iloc[546, 7])

3

### Q5

In [10]:
df['Locality'].unique()

array(['Waterbury', 'Bridgeport', 'Greenwich', 'Norwalk', nan,
       'Fairfield', 'West Hartford', 'Stamford'], dtype=object)

### Q6

In [11]:
df.isna().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [12]:
null_count = df.isna().sum()
print(list(null_count[ null_count != 0 ].index))

['Locality', 'Estimated Value', 'Property', 'carpet_area']

### Q7

In [13]:
null_count = df.isna().sum()
print(list(null_count[ null_count == null_count.max() ].index))

['Property']

### Q8

In [14]:
df[ df.isnull().sum(axis=1) <= 2 ].shape[0]

9917

## Q9

In [15]:
df[ df.isnull().sum(axis=1) == 0 ].shape[0]

5449