## SEP 2026 - MLP - Practice Assignment 1
### Week 1 Pandas

### Data Loading

In [1]:
import numpy as np
import pandas as pd

Check your data properly with the assignment

In [2]:
df = pd.read_csv('https://drive.google.com/uc?id=1zP38WCdZQ9StsAHTTLk72763QJQkhWrG')

In [3]:
df.shape

(9450, 13)

In [4]:
'Price' in df.columns

True

In [5]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0

### Q1

In [6]:
avg_price = df['Price'].mean()
print(f"{avg_price:.2f}")

9027.90

### Q2

In [7]:
df.groupby('Month').count()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,WeekDay,Day
Month,,,,,,,,,,,,
3,2388,2388,2388,2388,2388,2388,2388,2334,2388,2388,2388,2335
4,926,926,926,926,926,926,926,901,926,926,926,902
5,3092,3092,3092,3091,3092,3092,3092,3029,3092,3092,3092,3004
6,3044,3044,3044,3044,3044,3044,3044,2986,3044,3044,3044,2973

In [8]:
df['Month'].value_counts()

Month
5    3092
6    3044
3    2388
4     926
Name: count, dtype: int64

May

### Q3

In [9]:
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
weekends = ['Saturday', 'Sunday']

In [10]:
print(f'Avg Price on weekdays: {df[df['WeekDay'].isin(weekdays)]['Price'].mean()}')
print(f'Avg Price on weekends: {df[df['WeekDay'].isin(weekends)]['Price'].mean()}')

Avg Price on weekdays: 9015.219666215608
Avg Price on weekends: 9058.016077170418

Weekends

### Q4

In [11]:
df['Additional_Info'].unique()

array(['In-flight meal not included', 'No info',
       'No check-in baggage included', '1 Long layover',
       'Change airports', 'No Info', '2 Long layover', '1 Short layover',
       'Business class'], dtype=object)

In [12]:
df['Additional_Info'] = df['Additional_Info'].replace('No Info', 'No info')

In [13]:
df['Additional_Info'].unique()

array(['In-flight meal not included', 'No info',
       'No check-in baggage included', '1 Long layover',
       'Change airports', '2 Long layover', '1 Short layover',
       'Business class'], dtype=object)

In [14]:
df[ (df['Airline'] == 'IndiGo') & (df['Additional_Info'] == 'No info') ].shape[0]

1650

### Q5

In [15]:
df['Duration'].head(1)

0    26h 35m
Name: Duration, dtype: object

In [16]:
print(df['Duration'].isnull().sum())

0

In [28]:
def seconds(duration_str:str):
    # Example duration_str = 26h 35m
    duration_str = duration_str.strip()
    duration_str = duration_str.split(' ')
    if len(duration_str) == 2:
        hours = duration_str[0][:-1]
        hours = int(hours)
        minutes = duration_str[1][:-1]
        minutes = int(minutes)
    elif len(duration_str) == 1:
        if 'h' in duration_str[0]:
            hours = duration_str[0][:-1]
            hours = int(hours)
            minutes = 0
        elif 'm' in duration_str[0]:
            minutes = duration_str[0][:-1]
            minutes = int(minutes)
            hours = 0
    else:
        raise ValueError("Invalid duration format")

    return hours*60*60 + minutes*60

In [29]:
# Exmaple
print( seconds( '26h 35m' ) )
print( seconds( '26h 35m' ) == 26*60*60 + 35*60 )

print( seconds( '26h' ) )
print( seconds( '26h' ) == 26*60*60 + 0*60 )

95700
True
93600
True

In [30]:
df['Duration'].apply(seconds).mean()

np.float64(38957.93650793651)

In [31]:
avg_seconds = df['Duration'].apply(seconds).mean()
print(f"{avg_seconds:.2f}")

38957.94

### Q6

In [ ]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0

In [ ]:
df['Dep_Time'] = df['Dep_Time'].apply(lambda x: int(x[:2]))
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x: int(x[:2]))

In [ ]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20,4,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16,19,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0

In [ ]:
def time_category(value:int):
    if value < 5:
        return 'Night'
    elif value < 12:
        return 'Morning'
    elif value < 17:
        return 'Afternoon'
    elif value < 20:
        return 'Evening'
    else:
        return 'Night'

In [ ]:
df['Dep_Time'] = df['Dep_Time'].apply(time_category)
df['Arrival_Time'] = df['Arrival_Time'].apply(time_category)

In [ ]:
df['Dep_Time'].unique()

array(['Night', 'Afternoon', 'Evening', 'Morning'], dtype=object)

In [ ]:
df['Arrival_Time'].unique()

array(['Night', 'Evening', 'Morning', 'Afternoon'], dtype=object)

In [ ]:
df[ (df['Dep_Time'] == 'Morning') & (df['Arrival_Time'] == 'Evening') ].shape[0]

922

### Q7

In [ ]:
df['WeekDay'].map({'Monday': 0, 'Tuesday': 0, 'Wednesday': 0, 'Thursday': 0, 'Friday': 0, 'Saturday': 1, 'Sunday': 1}).value_counts()

WeekDay
0    6651
1    2799
Name: count, dtype: int64

Weekdays